name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on new tags matching 'v*'
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Install dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -v -o ask-linux-${{ matrix.arch }} ./cmd/ask

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ask-linux-${{ matrix.arch }}
        path: ask-linux-${{ matrix.arch }}
        retention-days: 5

  release:
    needs: build
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) ||
      github.event_name == 'release'
    runs-on: ubuntu-24.04

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}